version: '3'
services:
  terraform:
    build:
      args:
        - TERRAFORM_UID=${TERRAFORM_UID}
        - TERRAFORM_USER=${TERRAFORM_USER}
        - TERRAFORM_HOME=${HOME}
        - DOCKER_GID=${DOCKER_GID}
        - DOCKER_GROUP=${DOCKER_GROUP}
      context: docker/terraform
    container_name: ${COMPOSE_PROJECT_NAME}-terraform
    entrypoint: ash
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    network_mode: host
    tty: true
    user: ${TERRAFORM_USER}:${DOCKER_GROUP}
    volumes:
      - ${PWD}/node:${PWD}/node
      - ${PWD}/terraform:${PWD}/terraform
      - /var/run/docker.sock:/var/run/docker.sock
      - terraform-vscode-server:${TERRAFORM_HOME}/.vscode-server
    working_dir: ${PWD}/terraform
volumes:
  terraform-vscode-server:
